---
- hosts: all
  sudo: yes
  tasks:
    - name: check if apt is updated
      apt: cache_valid_time=3600 update-cache=yes
    - name: Install required system packages.
      apt: "pkg=python-dev state=installed"
    - name: Install python-software-properties for ppa module
      apt: "pkg=python-software-properties state=installed"
    - name: add ubuntugis ppa for newer gdal
      apt_repository: repo='ppa:ubuntugis/ubuntugis-unstable'
    - name: add Mapnik PPA
      apt_repository: repo='ppa:mapnik/v2.2.0'
    - name: add OSM PPA
      apt_repository: repo='ppa:kakrueger/openstreetmap'
    - name: Install GDAL bin from PPA
      apt: "pkg=gdal-bin=1.10.0-1~precise1 state=installed"
    - name: Install GDAL headers from PPA
      apt: "pkg=libgdal-dev state=installed"
    - name: Install libmapnik
      apt: "pkg=libmapnik=2.2.0-ubuntu1~precise2 state=installed"
    - name: Install mapnik python bindings
      apt: "pkg=python-mapnik state=installed"
    - name: Install postgis
      apt: "pkg=postgresql-9.1-postgis-2.0 state=installed"
    - name: Install osm2pgsql
      apt: "pkg=osm2pgsql state=installed"
