---
- hosts: all
  sudo: yes
  tasks:
    - name: check if apt is updated
      apt: cache_valid_time=3600 update-cache=yes
    - name: Install My SQL Core 5.5
      apt: "pkg=mysql-client-core-5.5 state=installed"
    - name: Install My SQL Server
      apt: "pkg=mysql-server state=installed"
    - name: Install My SQL Client
      apt: "pkg=mysql-client state=installed"
    - name: Install Apache 2
      apt: "pkg=apache2 state=installed"
    - name: Install PHP 5
      apt: "pkg=php5 state=installed"
    - name: Enable PHP-MySql
      apt: "pkg=php5-mysql state=installed"
